openapi: 3.0.0
info:
  title: API for DB tables.
  description: This is a simple API for managing DB tables (CRUD).
  version: 1.0.0
servers:
  - url: http://localhost:2507
paths:
  /Database/Excel/ReadAllRows:
    post:
      summary: Get all rows of Excel table.
      operationId: ReadAllRows
      tags:
        - Excel
      requestBody:
        description: The table to get from.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Excel/Req_Excel_All_Rows'
      responses:
        '200':
          description: The rows of the table.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Res_Excel_All_Rows'
        '500':
          description: "Some kide of error";
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Error'
  /Database/Excel/ReadRow/{Id}:
    post:
      summary: Get single row by id.
      operationId: GetRowById
      tags:
        - Excel
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type: int
      requestBody:
        description: "The table to get from, The name of the column id.";
          content:
          application/json:
            schema:
              $ref: '#/components/schemas/Excel/Req_Excel_Row'
      responses:
        '200':
          description: The row.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Res_Excel_Row'
        '500':
          description: "Some kide of error.";
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Error'
  /Database/Excel/AddRow:
    post:
      summary: Add row to the Excel table.
      operationId: AddRow
      tags:
        - Excel
      requestBody:
        description: The column value(file_Path).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Excel/Req_Add_Row'
      responses:
        '200':
          description: The new id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Res_Add_Row'
        '500':
          description: "Some kide of error.";
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Error'
  /Database/Excel/UpdateRow/{Id}:
    post:
      summary: Update row of Excel table.
      operationId: UpdateRow
      tags:
        - Excel
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type: int
      requestBody:
        description: The column value(file_Path).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Excel/Req_Add_Row'
      responses:
        '200':
          description: The new id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Res_Add_Row'
        '500':
          description: "Some kide of error.";
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Error'
  /Database/Excel/DeleteRow/{Id}:
    delete:
      summary: delete row of Excel table.
      operationId: deleteRow
      tags:
        - Excel
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type: int
      requestBody:
        description: "The table to get from, The name of the column id";
          content:
          application/json:
            schema:
              $ref: '#/components/schemas/Excel/Req_Excel_Row'
      responses:
        '200':
          description: Massage.
          content:
            application/json:
              schema:
                type: object
                  properties:
                    message:
                      type: string
        '500':
          description: "Some kide of error.";
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/Excel/Error'
components:
  schemas:
    Excel:
      Excel_Row:
        type: object
          properties:
            File_ID:
            type: int
            File_Path:
            type: string
      Req_Excel_All_Rows:
        type: object
          properties:
            Table_Name:
            type: string
          required:
            - Table_Name

      Res_Excel_All_Rows:
        type: array
          items:
            $ref: '#/components/schemas/Excel/Excel_Row'
      Req_Excel_Row:
        type: object
          properties:
            Table_Name:
            type: string
            Column_Name:
            type: string
          required:
            - Table_Name
            - Column_Name
      Res_Excel_Row:
        type: array
          items:
            $ref: '#/components/schemas/Excel/Excel_Row'
      Req_Add_Row:
        type: object
          properties:
            File_Path:
            type: string
          required:
            - File_Path
      Res_Add_Row:
        type: array
          items:
            type: object
              properties:
                New_ID:
                type: int
      Error:
        type: object
          properties:
            message:
              type: string
        
